version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: always
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    # ports: # Enable if you want to expose your Elasticsearch DB
      # - "9200:9200"
      # - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1G -Xms256m"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  curator:
    build:
      context: extensions/curator/
    volumes:
      - type: bind
        source: ./extensions/curator/config/curator.yml
        target: /usr/share/curator/config/curator.yml
        read_only: true
      - type: bind
        source: ./extensions/curator/config/delete_log_files_curator.yml
        target: /usr/share/curator/config/delete_log_files_curator.yml
        read_only: true
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: always
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ./logstash/ssl/out/ca.crt
        target: /etc/ca.crt
        read_only: true
      - type: bind
        source: ./logstash/ssl/out/logstash.crt
        target: /etc/logstash.crt
        read_only: true
      - type: bind
        source: ./logstash/ssl/out/logstash.key
        target: /etc/logstash.key
        read_only: true
    ports:
      - "5044:5044"
      # - "5000:5000/tcp"
      # - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    # ports:
    #   - "5601:5601"
    environment: 
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    container_name: nginx
    image: nginx
    ports: 
        - 80:80
        - 443:443

    depends_on:
      - kibana
    restart: always
    volumes:
        - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
        - ./nginx/cert.cert:/etc/ssl/cert.cert:ro
        - ./nginx/cert.key:/etc/ssl/cert.key:ro
    networks: 
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
