actions:
  1:
    action: delete_indices
    description: >-
      Delete indices that are older than 64 days
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: kibana
      exclude: True
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 64
